# Generated by Django 5.2.14 on 2026-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
