# Generated by Django 5.2.14 on 2026-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='builder',
        ),
        migrations.AddField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
