# Generated by Django 5.2.14 on 2026-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
